---
- name: Add PostgreSQL APT repository
  become: true
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add PostgreSQL repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: present

- name: Update APT package index
  become: true
  ansible.builtin.apt:
    update_cache: yes

- name: Install PostgreSQL 16
  become: true
  ansible.builtin.apt:
    name: postgresql-16
    state: present

- name: Start and enable PostgreSQL service
  become: true
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes
