---
# tasks file for debian11_config_role
- name: Setting Time
  become: true
  ansible.builtin.apt:
    name: ntp
    state: present

- name: Setting Timezone
  become: true
  community.general.timezone:
    name: "{{ debian11_config_role_timezone }}"

- name: Apt Update
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Apt Upgrade
  become: true
  ansible.builtin.apt:
    upgrade: dist

- name: Install Some Packages
  become: true
  ansible.builtin.apt:
    name: "{{ debian11_config_role_packages }}"
    state: present

- name: Setting Hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ debian11_config_role_hostname }}"

- name: Checking System Status
  become: true
  ansible.builtin.command: uptime
  register: uptime_result
  changed_when: false
