---
- name: postgresql apt rep
  become: true
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: add local postgresql rep
  become: true
  ansible.builtin.apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: present

- name: apt update
  become: true
  ansible.builtin.apt:
    update_cache: yes

- name: install postgresql 16
  become: true
  ansible.builtin.apt:
    name: postgresql-16
    state: present

- name: start postgresql 16
  become: true
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes
