all:
  hosts:
    localhost
  children:
    postgres-server:
      hosts:
        192.168.0.108:
          ansible_user: "{{ main_user }}"
          ansible_password: "{{ main_password }}"
          ansible_become_password: "{{ main_become_password }}"
