all:
  hosts:
    localhost
  children:
    postgres-server:
      hosts:
        192.168.149.145:
          ansible_user: test
          ansible_password: "test"
          ansible_become_password: "test"
